
CREATE TABLE Shippers (
  ShipperID INT NOT NULL,
  CompanyName STRING NOT NULL,
  Phone STRING,
  PRIMARY KEY (ShipperID)
);

ALTER TABLE Shippers
  ALTER COLUMN ShipperID SET GENERATED ALWAYS AS IDENTITY;
